---
name: chimg
summary: A tool to modify images and chroots based on configuration
description: |
  A tool to modify images and chroots based on configuration.
version: git
base: core22
confinement: classic
license: GPL-3.0
issues: https://github.com/toabctl/chimg/issues
website: https://github.com/toabctl/chimg
source-code: https://github.com/toabctl/chimg
contact: thomas.bechtold@canonical.com

apps:
  chimg:
    command: bin/python $SNAP/bin/chimg

parts:
  chimg:
    plugin: python
    source: .
    # see https://forum.snapcraft.io/t/modulenotfounderror-exception-for-a-snap-built-in-classic-confinement-mode/31090
    override-build: |
      snapcraftctl build
      ln -sf ../usr/bin/python3.10 $SNAPCRAFT_PART_INSTALL/bin/python3
    build-packages:
      - rustc
    stage-packages:
      - squashfs-tools
      - python3-venv
      - python3.10-minimal
      - libpython3.10-minimal
      - libpython3.10-stdlib
